name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn run build

      - name: Run tests
        run: yarn run test:ci
        env:
          CI: true

      - name: Generate Code Coverage
        # only when running in node v16
        if: matrix.node == 16
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
